from yacs.config import CfgNode as CN
_C = CN()

_C.SYSTEM = CN()
_C.SYSTEM.NUM_WORKERS = 1
_C.SYSTEM.PIN_MEMORY = False
_C.SYSTEM.SAVE_ROOT = "/Users/kris/Downloads/github/RAM/experiments"
_C.SYSTEM.EXP_NAME = "default"
_C.SYSTEM.LOG_FREQ= 5


# Dataset Options
_C.DATASET = CN()
_C.DATASET.IMAGE_DIR="./RAM/data/"
_C.DATASET.NUM_CLASSES = 10

# Glimpse Network Options
_C.GLIMPSE_SENSOR = CN()
_C.GLIMPSE_SENSOR.NUM_SCALES= 2
_C.GLIMPSE_SENSOR.WIDTH = 12

# Glimpse Network Options
_C.GLIMPSE_NETWORK = CN()
_C.GLIMPSE_NETWORK.HIDDEN_SIZE = 128
_C.GLIMPSE_NETWORK.OUT_SIZE = 256
_C.GLIMPSE_NETWORK.NUM_GLIMPSE = 1
_C.GLIMPSE_NETWORK.NUM_CHANNELS = 1

# RNN Network Options
_C.CORE_NETWORK= CN()
_C.CORE_NETWORK.HIDDEN_SIZE = 256

# Train
_C.TRAIN = CN()
_C.TRAIN.ROOT = '/Users/kris/torch/data'
_C.TRAIN.BATCH_SIZE = 100
_C.TRAIN.NUM_EPOCHS = 1000
_C.TRAIN.NUM_DATA_POINTS = 1000

# Optimizer Options
_C.TRAIN.OPTIMIZER = CN()
_C.TRAIN.OPTIMIZER.lr= 3e-2
_C.TRAIN.OPTIMIZER.weight_decay= 0.0001
_C.TRAIN.OPTIMIZER.NAME = 'Adam'
# Adam
_C.TRAIN.OPTIMIZER.ADAM = CN()
_C.TRAIN.OPTIMIZER.ADAM.betas = (0.9, 0.999)
# SGD
_C.TRAIN.OPTIMIZER.SGD = CN()
_C.TRAIN.OPTIMIZER.momentum = 0.9

_C.TRAIN.SCHEDULER = CN()
_C.TRAIN.SCHEDULER.NAME = 'ReduceLROnPlateau'
# PlateuL
_C.TRAIN.SCHEDULER.REDUCELRONPLATEAU = CN()
_C.TRAIN.SCHEDULER.REDUCELRONPLATEAU.patience= 100
_C.TRAIN.SCHEDULER.REDUCELRONPLATEAU.threshold= 1e-8
# StepLr
_C.TRAIN.SCHEDULER.STEPLR = CN()
_C.TRAIN.SCHEDULER.STEPLR.step_size = 5

_C.VAL= CN()
_C.VAL.BATCH_SIZE = 2
_C.VAL.PAITENCE = 10


_C.TEST = CN()
_C.TEST.BATCH_SIZE = 12

cfg = _C
