from yacs.config import CfgNode as CN
_C = CN()

_C.SYSTEM = CN()
_C.SYSTEM.NUM_WORKERS = 1
_C.SYSTEM.PIN_MEMORY = False
_C.SYSTEM.SAVE_ROOT = "/Users/kris/Downloads/github/RAM/experiments"
_C.SYSTEM.EXP_NAME = "default"
_C.SYSTEM.LOG_FREQ= 5

# Glimpse Network Options
_C.GLIMPSE_SENSOR = CN()
_C.GLIMPSE_SENSOR.NUM_SCALES= 2
_C.GLIMPSE_SENSOR.WIDTH = 12

# Glimpse Network Options
_C.GLIMPSE_NETWORK = CN()
_C.GLIMPSE_NETWORK.HIDDEN_SIZE = 128
_C.GLIMPSE_NETWORK.OUT_SIZE = 256
_C.GLIMPSE_NETWORK.NUM_GLIMPSE = 1
_C.GLIMPSE_NETWORK.NUM_CHANNELS = 1

# RNN Network Options
_C.CORE_NETWORK= CN()
_C.CORE_NETWORK.HIDDEN_SIZE = 256

# Train Data
_C.DATA = CN()
_C.DATA.ROOT = '/Users/kris/torch/data'
_C.DATA.NUM_DATA_POINTS = 1000
_C.DATA.NUM_CLASSES = 10

# Optimizer Options
_C.SOLVER = CN()
_C.SOLVER.LR = 3e-2
_C.SOLVER.WEIGHT_DECAY = 0.0001
_C.SOLVER.BETAS = (0.9, 0.999)
_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.patience= 100
_C.SOLVER.THRESHOLD= 1e-8
_C.SOLVER.STEP_SIZE = 5
_C.SOLVER.NUM_EPOCHS = 100
_C.SOLVER.BATCH_SIZE = 100
_C.SOLVER.PAITENCE = 10


_C.VAL= CN()
_C.TEST = CN()

cfg = _C
